 jaffle_shop:
   target: databricks_job
   outputs:
     databricks_job:
      type: databricks
      method: http
      catalog: "junaid_demos"
      schema: "jaffle_shop_default"
      host: ""
      http_path: ""
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"
